"""
Module Director — ANASTASiA's dynamic API orchestration engine.

The Director reads knowledge cards from the Module Registry and creates
optimal call chains across all configured modules. It decides:

1. Which modules to search (based on credentials + capabilities)
2. What order to call them (priority-based)
3. How to merge results (dedup, price comparison, cheapest wins)
4. How to route bookings (to the right module based on source)

This is the "neuron delegation" layer for API orchestration.
ANASTASiA doesn't hardcode which APIs to call — she reads knowledge
cards and dynamically creates the optimal pipeline.

MYSTES KYRIOS LLC — Confidential.
"""

import logging
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Tuple

from .registry import (
    APIModule,
    KnowledgeCard,
    ModuleRegistry,
    SourceType,
    VerticalType,
)

logger = logging.getLogger("anastasia.modules.director")


@dataclass
class SearchPlan:
    """
    A plan for searching across multiple modules.

    Generated by the Director based on available credentials,
    module capabilities, and search requirements.
    """
    modules: List[str]              # Module IDs to search, in priority order
    primary: str                    # Primary module (highest priority)
    benchmark: Optional[str] = None # Price benchmark module (e.g., Google)
    merge_strategy: str = "cheapest_wins"  # How to merge results
    dedup_window_minutes: int = 15  # Time window for dedup matching
    estimated_sources: int = 0
    notes: List[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "modules": self.modules,
            "primary": self.primary,
            "benchmark": self.benchmark,
            "merge_strategy": self.merge_strategy,
            "dedup_window_minutes": self.dedup_window_minutes,
            "estimated_sources": self.estimated_sources,
            "notes": self.notes,
        }


@dataclass
class BookingRoute:
    """
    Routing decision for a booking — which module handles it.
    """
    module_id: str
    module_name: str
    booking_steps: List[str]
    passenger_format: Dict[str, Any]
    date_format: str
    notes: str = ""


class ModuleDirector:
    """
    ANASTASiA's intelligent API orchestration engine.

    Reads knowledge cards from the Module Registry and makes
    dynamic routing decisions for search, booking, and management.

    Like the neuron network delegates between neurons, the Director
    delegates between API modules based on their knowledge cards.
    """

    def __init__(self, registry: ModuleRegistry):
        self.registry = registry

    # =========================================================================
    # SEARCH PLANNING
    # =========================================================================

    def plan_search(
        self,
        vertical: str = VerticalType.FLIGHTS.value,
        origin: Optional[str] = None,
        destination: Optional[str] = None,
        requirements: Optional[Dict[str, Any]] = None,
    ) -> SearchPlan:
        """
        Create an optimal search plan based on available modules.

        Reads knowledge cards, checks credentials, and returns a
        prioritized list of modules to search with merge strategy.

        Args:
            vertical: Which vertical to search (flights, hotels, etc.)
            origin/destination: Route context (for geographic optimization)
            requirements: Optional constraints (nonstop_only, cabin_class, etc.)

        Returns:
            SearchPlan with modules to search and merge strategy
        """
        # Get all configured modules for this vertical
        available = self.registry.list_configured(vertical=vertical)
        if not available:
            return SearchPlan(
                modules=[],
                primary="none",
                notes=["No configured modules for this vertical"],
            )

        # Sort by priority (highest first)
        available.sort(key=lambda m: m.knowledge_card.priority, reverse=True)

        module_ids = [m.knowledge_card.module_id for m in available]
        primary = module_ids[0] if module_ids else "none"

        # Build notes about what each source provides
        notes = []
        for mod in available:
            card = mod.knowledge_card
            strengths = ", ".join(card.strengths[:3]) if card.strengths else card.source_type
            notes.append(f"{card.name}: {strengths} ({card.carrier_count} carriers)")

        # Determine merge strategy
        has_arbitrage = any(
            "pos_arbitrage" in m.knowledge_card.strengths
            for m in available
        )
        merge = "cheapest_wins_with_arbitrage" if has_arbitrage else "cheapest_wins"

        return SearchPlan(
            modules=module_ids,
            primary=primary,
            merge_strategy=merge,
            estimated_sources=len(module_ids),
            notes=notes,
        )

    def get_search_modules(
        self,
        vertical: str = VerticalType.FLIGHTS.value,
    ) -> List[APIModule]:
        """
        Get configured modules for searching, sorted by priority.

        This is what search_global() calls to know which modules to fire.
        """
        return self.registry.list_configured(vertical=vertical)

    # =========================================================================
    # BOOKING ROUTING
    # =========================================================================

    def route_booking(
        self,
        source: str,
        module_id: Optional[str] = None,
    ) -> Optional[BookingRoute]:
        """
        Determine which module should handle a booking.

        Based on the flight's source (gds, ndc, aggregator) or
        explicit module_id from search results.

        Args:
            source: Source type from search result (e.g., "gds", "ndc", "aggregator")
            module_id: Explicit module ID (overrides source-based routing)

        Returns:
            BookingRoute with module details and passenger format
        """
        if module_id:
            mod = self.registry.get(module_id)
            if mod and mod.is_configured:
                return self._build_route(mod)

        # Route by source type
        source_map = {
            "gds": SourceType.GDS.value,
            "ndc": SourceType.NDC.value,
            "aggregator": SourceType.AGGREGATOR.value,
            "direct": SourceType.DIRECT.value,
            "wholesaler": SourceType.WHOLESALER.value,
        }
        target_type = source_map.get(source, source)

        modules = self.registry.list_modules(source_type=target_type, configured_only=True)
        if modules:
            return self._build_route(modules[0])

        return None

    def _build_route(self, mod: APIModule) -> BookingRoute:
        """Build a BookingRoute from a module."""
        card = mod.knowledge_card
        return BookingRoute(
            module_id=card.module_id,
            module_name=card.name,
            booking_steps=card.booking_steps,
            passenger_format=card.passenger_format,
            date_format=card.date_format,
            notes=card.booking_notes,
        )

    # =========================================================================
    # CAPABILITY QUERIES
    # =========================================================================

    def can_search(self, vertical: str = VerticalType.FLIGHTS.value) -> bool:
        """Check if any configured module can search this vertical."""
        modules = self.registry.list_configured(vertical=vertical)
        return any(
            m.knowledge_card.capabilities.get("search", False)
            for m in modules
        )

    def can_book(self, vertical: str = VerticalType.FLIGHTS.value) -> bool:
        """Check if any configured module can book in this vertical."""
        modules = self.registry.list_configured(vertical=vertical)
        return any(
            m.knowledge_card.capabilities.get("book", False)
            for m in modules
        )

    def get_capabilities(self, vertical: Optional[str] = None) -> Dict[str, List[str]]:
        """
        Get a capability matrix across all configured modules.

        Returns:
            {"search": ["picasso", "duffel", "kiwi"],
             "book": ["picasso", "duffel"],
             "cancel": ["duffel"],
             ...}
        """
        cap_map: Dict[str, List[str]] = {}
        modules = self.registry.list_configured(vertical=vertical)
        for mod in modules:
            card = mod.knowledge_card
            for cap, enabled in card.capabilities.items():
                if enabled:
                    cap_map.setdefault(cap, []).append(card.module_id)
        return cap_map

    def get_verticals(self) -> Dict[str, dict]:
        """
        Get status of all verticals.

        Returns:
            {"flights": {"configured": 3, "total": 5, "can_search": True, "can_book": True},
             "hotels": {"configured": 1, "total": 2, "can_search": True, "can_book": True},
             ...}
        """
        verticals = {}
        for vt in VerticalType:
            all_modules = self.registry.list_modules(vertical=vt.value)
            configured = self.registry.list_configured(vertical=vt.value)
            verticals[vt.value] = {
                "configured": len(configured),
                "total": len(all_modules),
                "can_search": self.can_search(vt.value),
                "can_book": self.can_book(vt.value),
                "modules": [m.knowledge_card.name for m in configured],
            }
        return verticals

    # =========================================================================
    # KNOWLEDGE SYNTHESIS
    # =========================================================================

    def generate_system_prompt(self, vertical: Optional[str] = None) -> str:
        """
        Generate a system prompt section from all configured module knowledge cards.

        ANASTASiA reads this to understand what modules are available,
        what they can do, and how to use them.
        """
        modules = self.registry.list_configured(vertical=vertical)
        if not modules:
            return ""

        lines = [
            "\n## AVAILABLE API MODULES",
            f"You have {len(modules)} configured API source(s). "
            "Use the appropriate tools for each source based on the query.",
            "",
        ]

        for mod in modules:
            lines.append(mod.knowledge_card.to_prompt())
            lines.append("")

        # Add routing guidance
        lines.append("### ROUTING GUIDANCE")
        lines.append("When searching, use ALL configured sources for comprehensive results.")
        lines.append("When booking, route to the module that provided the selected flight.")
        lines.append("The `source` field in search results tells you which module to use.")

        return "\n".join(lines)

    def generate_dashboard(self) -> str:
        """Generate a text dashboard for the admin terminal."""
        lines = [
            "╔══════════════════════════════════════════════════════════╗",
            "║          ANASTASiA Module Director — Dashboard          ║",
            "╚══════════════════════════════════════════════════════════╝",
            "",
        ]

        verticals = self.get_verticals()
        for vt, info in verticals.items():
            if info["total"] == 0:
                continue
            status = "✓" if info["can_search"] else "✗"
            lines.append(f"  {status} {vt.upper()}: {info['configured']}/{info['total']} sources active")
            for name in info["modules"]:
                lines.append(f"      ● {name}")
            lines.append("")

        caps = self.get_capabilities()
        if caps:
            lines.append("  CAPABILITIES:")
            for cap, modules in sorted(caps.items()):
                lines.append(f"    {cap}: {', '.join(modules)}")

        return "\n".join(lines)
