"""
Bridge Orchestrator — The intelligence that understands both sides.

The orchestrator is the brain of the bridge. It takes structural knowledge
from both entities and:
1. Identifies integration opportunities
2. Generates proposals for EACH side independently
3. Ensures proposals are entity-scoped (A only sees A's proposals)
4. Finds the most efficient way to connect systems

The orchestrator NEVER has access to source code. It works entirely from
structural knowledge (API patterns, schemas, auth flows, integration points).

MYSTES KYRIOS LLC — Confidential.
"""

import logging
import time
from typing import Any, Dict, List, Optional

from ..core.events import Event, EventBus, EventType
from ..core.types import BridgeProposal, StructuralKnowledge

logger = logging.getLogger(__name__)


# Integration opportunity patterns
OPPORTUNITY_PATTERNS = [
    {
        "name": "webhook_bridge",
        "description": "Connect systems via webhook events",
        "requires_a": ["integration_points"],
        "requires_b": ["api_patterns"],
    },
    {
        "name": "api_adapter",
        "description": "Create API adapter for cross-system calls",
        "requires_a": ["api_patterns"],
        "requires_b": ["api_patterns"],
    },
    {
        "name": "schema_mapping",
        "description": "Map data schemas between systems",
        "requires_a": ["data_schemas"],
        "requires_b": ["data_schemas"],
    },
    {
        "name": "auth_bridge",
        "description": "Bridge authentication between systems",
        "requires_a": ["auth_flows"],
        "requires_b": ["auth_flows"],
    },
    {
        "name": "event_sync",
        "description": "Synchronize events between systems",
        "requires_a": ["integration_points"],
        "requires_b": ["integration_points"],
    },
]


class BridgeOrchestrator:
    """
    Bridge Orchestrator — Generates integration proposals from structural knowledge.

    Takes structural knowledge from both sides of a bridge and generates
    proposals that improve their integration. Each proposal targets ONE
    entity — the other side never sees it.
    """

    def __init__(self, event_bus: Optional[EventBus] = None):
        self._event_bus = event_bus
        self._proposals: Dict[str, List[BridgeProposal]] = {}  # bridge_id -> proposals

    def analyze_integration_opportunities(
        self,
        bridge_id: str,
        knowledge_a: StructuralKnowledge,
        knowledge_b: StructuralKnowledge,
    ) -> List[Dict[str, Any]]:
        """
        Analyze structural knowledge from both sides and identify
        integration opportunities.

        Does NOT generate proposals — just identifies WHERE improvements
        can be made. Proposals are generated by generate_proposals().

        Args:
            bridge_id: Which bridge to analyze.
            knowledge_a: Structural knowledge from entity A.
            knowledge_b: Structural knowledge from entity B.

        Returns:
            List of opportunity dicts with type, description, and confidence.
        """
        opportunities = []

        # 1. Find matching/complementary API patterns
        api_opps = self._find_api_opportunities(knowledge_a, knowledge_b)
        opportunities.extend(api_opps)

        # 2. Find schema mapping opportunities
        schema_opps = self._find_schema_opportunities(knowledge_a, knowledge_b)
        opportunities.extend(schema_opps)

        # 3. Find auth bridging opportunities
        auth_opps = self._find_auth_opportunities(knowledge_a, knowledge_b)
        opportunities.extend(auth_opps)

        # 4. Find webhook/event sync opportunities
        event_opps = self._find_event_opportunities(knowledge_a, knowledge_b)
        opportunities.extend(event_opps)

        logger.info(
            "Found %d integration opportunities for bridge %s",
            len(opportunities), bridge_id,
        )

        return opportunities

    def generate_proposals(
        self,
        bridge_id: str,
        target_entity_id: str,
        knowledge_a: StructuralKnowledge,
        knowledge_b: StructuralKnowledge,
        opportunities: Optional[List[Dict[str, Any]]] = None,
    ) -> List[BridgeProposal]:
        """
        Generate integration proposals for a specific entity.

        Proposals are entity-scoped: they describe changes to the TARGET
        entity's codebase. The source context explains WHY the change is
        needed (integration requirement) without revealing HOW the other
        side works internally.

        Args:
            bridge_id: Which bridge.
            target_entity_id: WHO this proposal is for.
            knowledge_a: Structural knowledge from entity A.
            knowledge_b: Structural knowledge from entity B.
            opportunities: Pre-computed opportunities (optional).

        Returns:
            List of BridgeProposal for the target entity.
        """
        if not opportunities:
            opportunities = self.analyze_integration_opportunities(
                bridge_id, knowledge_a, knowledge_b
            )

        proposals = []

        # Determine which knowledge belongs to target and which to partner
        if target_entity_id == knowledge_a.entity_id:
            target_knowledge = knowledge_a
            partner_knowledge = knowledge_b
        else:
            target_knowledge = knowledge_b
            partner_knowledge = knowledge_a

        for opp in opportunities:
            proposal = self._generate_proposal_for_opportunity(
                bridge_id=bridge_id,
                target_entity_id=target_entity_id,
                target_knowledge=target_knowledge,
                partner_knowledge=partner_knowledge,
                opportunity=opp,
            )
            if proposal:
                proposals.append(proposal)

        # Store proposals
        if bridge_id not in self._proposals:
            self._proposals[bridge_id] = []
        self._proposals[bridge_id].extend(proposals)

        # Publish event
        if self._event_bus and proposals:
            self._event_bus.publish(Event(
                type=EventType.BRIDGE_PROPOSAL_SENT,
                source="bridge.orchestrator",
                data={
                    "bridge_id": bridge_id,
                    "target_entity_id": target_entity_id,
                    "proposal_count": len(proposals),
                    "proposal_ids": [p.id for p in proposals],
                },
            ))

        logger.info(
            "Generated %d proposals for entity %s on bridge %s",
            len(proposals), target_entity_id[:8], bridge_id,
        )

        return proposals

    def approve_proposal(
        self,
        proposal_id: str,
        approved_by: str,
    ) -> Optional[BridgeProposal]:
        """Approve a proposal (entity-scoped — only the target entity can approve)."""
        proposal = self._find_proposal(proposal_id)
        if not proposal:
            return None

        proposal.status = "approved"
        proposal.approved_by = approved_by
        proposal.approved_at = time.time()

        if self._event_bus:
            self._event_bus.publish(Event(
                type=EventType.BRIDGE_PROPOSAL_APPROVED,
                source="bridge.orchestrator",
                data={
                    "bridge_id": proposal.bridge_id,
                    "proposal_id": proposal_id,
                    "target_entity_id": proposal.target_entity_id,
                },
            ))

        return proposal

    def reject_proposal(
        self,
        proposal_id: str,
        reason: str = "",
    ) -> Optional[BridgeProposal]:
        """Reject a proposal."""
        proposal = self._find_proposal(proposal_id)
        if not proposal:
            return None

        proposal.status = "rejected"

        if self._event_bus:
            self._event_bus.publish(Event(
                type=EventType.BRIDGE_PROPOSAL_REJECTED,
                source="bridge.orchestrator",
                data={
                    "bridge_id": proposal.bridge_id,
                    "proposal_id": proposal_id,
                    "reason": reason,
                },
            ))

        return proposal

    def get_proposals(
        self,
        bridge_id: str,
        target_entity_id: Optional[str] = None,
        status: Optional[str] = None,
    ) -> List[BridgeProposal]:
        """Get proposals for a bridge, filtered by entity and/or status."""
        proposals = self._proposals.get(bridge_id, [])

        if target_entity_id:
            proposals = [
                p for p in proposals
                if p.target_entity_id == target_entity_id
            ]

        if status:
            proposals = [p for p in proposals if p.status == status]

        return proposals

    @property
    def total_proposals(self) -> int:
        return sum(len(v) for v in self._proposals.values())

    # ------------------------------------------------------------------
    # Opportunity finders
    # ------------------------------------------------------------------

    def _find_api_opportunities(
        self,
        ka: StructuralKnowledge,
        kb: StructuralKnowledge,
    ) -> List[Dict[str, Any]]:
        """Find API integration opportunities between two systems."""
        opportunities = []

        # Look for complementary endpoints (e.g., one has booking, other has payment)
        a_purposes = {
            p.get("purpose", "").lower() for p in ka.api_patterns if p.get("purpose")
        }
        b_purposes = {
            p.get("purpose", "").lower() for p in kb.api_patterns if p.get("purpose")
        }

        # Find purposes that exist on one side but not the other
        a_unique = a_purposes - b_purposes
        b_unique = b_purposes - a_purposes

        if a_unique or b_unique:
            opportunities.append({
                "type": "api_adapter",
                "description": "Create API adapters for cross-system functionality",
                "confidence": 0.7,
                "details": {
                    "a_unique_capabilities": list(a_unique)[:10],
                    "b_unique_capabilities": list(b_unique)[:10],
                },
            })

        # Find matching endpoints that could be bridged
        common = a_purposes & b_purposes
        if common:
            opportunities.append({
                "type": "api_bridge",
                "description": "Bridge common API patterns for unified access",
                "confidence": 0.8,
                "details": {
                    "common_patterns": list(common)[:10],
                },
            })

        return opportunities

    def _find_schema_opportunities(
        self,
        ka: StructuralKnowledge,
        kb: StructuralKnowledge,
    ) -> List[Dict[str, Any]]:
        """Find data schema mapping opportunities."""
        opportunities = []

        if ka.data_schemas and kb.data_schemas:
            # Find similar model names
            a_models = set(ka.data_schemas.keys())
            b_models = set(kb.data_schemas.keys())

            # Exact matches
            common_models = a_models & b_models
            if common_models:
                opportunities.append({
                    "type": "schema_mapping",
                    "description": f"Map {len(common_models)} common data models",
                    "confidence": 0.9,
                    "details": {"common_models": list(common_models)[:10]},
                })

            # Fuzzy matches (e.g., "Booking" vs "booking_record")
            for a_model in a_models:
                for b_model in b_models:
                    if a_model == b_model:
                        continue
                    # Simple fuzzy: one contains the other
                    a_lower = a_model.lower()
                    b_lower = b_model.lower()
                    if a_lower in b_lower or b_lower in a_lower:
                        opportunities.append({
                            "type": "schema_mapping",
                            "description": f"Potential mapping: {a_model} <-> {b_model}",
                            "confidence": 0.5,
                            "details": {
                                "model_a": a_model,
                                "model_b": b_model,
                            },
                        })

        return opportunities

    def _find_auth_opportunities(
        self,
        ka: StructuralKnowledge,
        kb: StructuralKnowledge,
    ) -> List[Dict[str, Any]]:
        """Find auth bridging opportunities."""
        opportunities = []

        if ka.auth_flows and kb.auth_flows:
            a_types = {f.get("type", "") for f in ka.auth_flows}
            b_types = {f.get("type", "") for f in kb.auth_flows}

            if a_types != b_types:
                opportunities.append({
                    "type": "auth_bridge",
                    "description": "Bridge different authentication systems",
                    "confidence": 0.6,
                    "details": {
                        "a_auth_types": list(a_types),
                        "b_auth_types": list(b_types),
                    },
                })

        return opportunities

    def _find_event_opportunities(
        self,
        ka: StructuralKnowledge,
        kb: StructuralKnowledge,
    ) -> List[Dict[str, Any]]:
        """Find webhook/event synchronization opportunities."""
        opportunities = []

        a_webhooks = [
            p for p in ka.integration_points if p.get("type") == "webhook"
        ]
        b_webhooks = [
            p for p in kb.integration_points if p.get("type") == "webhook"
        ]

        if a_webhooks or b_webhooks:
            opportunities.append({
                "type": "event_sync",
                "description": "Synchronize events between systems via webhooks",
                "confidence": 0.7,
                "details": {
                    "a_webhooks": len(a_webhooks),
                    "b_webhooks": len(b_webhooks),
                },
            })

        return opportunities

    # ------------------------------------------------------------------
    # Proposal generation
    # ------------------------------------------------------------------

    def _generate_proposal_for_opportunity(
        self,
        bridge_id: str,
        target_entity_id: str,
        target_knowledge: StructuralKnowledge,
        partner_knowledge: StructuralKnowledge,
        opportunity: Dict[str, Any],
    ) -> Optional[BridgeProposal]:
        """
        Generate a concrete proposal for one side of the bridge.

        The proposal describes changes to the TARGET entity's codebase.
        The source_context explains WHY without revealing the partner's code.
        """
        opp_type = opportunity.get("type", "")
        details = opportunity.get("details", {})

        if opp_type == "api_adapter":
            return BridgeProposal(
                bridge_id=bridge_id,
                target_entity_id=target_entity_id,
                source_context=(
                    "Integration partner provides complementary API capabilities. "
                    "Creating an adapter will enable unified access."
                ),
                action_type="propose_file_create",
                description=(
                    f"Create API adapter for {len(details.get('b_unique_capabilities', []))} "
                    f"partner capabilities"
                ),
                rationale=(
                    "Adapter enables your system to leverage partner capabilities "
                    "without modifying existing code. Changes are isolated to a "
                    "new adapter module."
                ),
                risk_level="low",
            )

        elif opp_type == "api_bridge":
            common = details.get("common_patterns", [])
            return BridgeProposal(
                bridge_id=bridge_id,
                target_entity_id=target_entity_id,
                source_context=(
                    f"Both systems share {len(common)} common API patterns. "
                    "A bridge layer will enable seamless interoperability."
                ),
                action_type="propose_file_create",
                description=f"Create bridge layer for {len(common)} common patterns",
                rationale=(
                    "Bridge layer normalizes shared patterns, reducing integration "
                    "friction and enabling real-time data flow."
                ),
                risk_level="low",
            )

        elif opp_type == "schema_mapping":
            return BridgeProposal(
                bridge_id=bridge_id,
                target_entity_id=target_entity_id,
                source_context=(
                    "Partner system uses compatible data models. A mapping layer "
                    "will enable data exchange without schema changes."
                ),
                action_type="propose_file_create",
                description="Create data model mapping layer",
                rationale=(
                    "Schema mapping enables interoperability without modifying "
                    "existing models. Transforms happen at the integration boundary."
                ),
                risk_level="low",
            )

        elif opp_type == "auth_bridge":
            return BridgeProposal(
                bridge_id=bridge_id,
                target_entity_id=target_entity_id,
                source_context=(
                    "Partner uses a different authentication method. An auth "
                    "bridge will enable cross-system authentication."
                ),
                action_type="propose_file_create",
                description="Create authentication bridge adapter",
                rationale=(
                    "Auth bridge translates between authentication systems, "
                    "enabling secure cross-system calls without sharing credentials."
                ),
                risk_level="medium",
            )

        elif opp_type == "event_sync":
            return BridgeProposal(
                bridge_id=bridge_id,
                target_entity_id=target_entity_id,
                source_context=(
                    "Partner system publishes events that your system could consume. "
                    "A webhook receiver will enable real-time synchronization."
                ),
                action_type="propose_file_create",
                description="Create webhook receiver for partner events",
                rationale=(
                    "Event synchronization enables real-time updates without "
                    "polling. Changes are isolated to a new webhook handler."
                ),
                risk_level="low",
            )

        return None

    def _find_proposal(self, proposal_id: str) -> Optional[BridgeProposal]:
        """Find a proposal across all bridges."""
        for proposals in self._proposals.values():
            for p in proposals:
                if p.id == proposal_id:
                    return p
        return None
