"""
Bridge Registry — Tracks all active bridges, their states, and knowledge stores.

The registry is the central index for all daemon bridges. It manages:
- Active bridge instances (contract + firewalls + knowledge stores)
- Bridge lookup by ID or entity
- Bridge statistics and health

Production: Backed by Redis/DB. Current: In-memory.

MYSTES KYRIOS LLC — Confidential.
"""

import logging
import time
from typing import Any, Dict, List, Optional

from ..core.events import Event, EventBus, EventType
from ..core.types import BridgeContract, BridgeState, StructuralKnowledge

from .contracts import ContractManager
from .extractor import StructuralKnowledgeExtractor
from .firewall import IPFirewall

logger = logging.getLogger(__name__)


class BridgeInstance:
    """
    A live bridge between two entities.

    Holds references to the contract, both firewalls, both knowledge stores,
    and the bridge orchestrator. This is the operational unit.
    """

    def __init__(
        self,
        contract: BridgeContract,
        firewall_a: IPFirewall,
        firewall_b: IPFirewall,
    ):
        self.contract = contract
        self.firewall_a = firewall_a   # Entity A's firewall
        self.firewall_b = firewall_b   # Entity B's firewall

        # Knowledge stores — what the cloud knows about each side
        self.knowledge_a: Optional[StructuralKnowledge] = None
        self.knowledge_b: Optional[StructuralKnowledge] = None

        # Proposals generated by the bridge
        self.proposals_for_a: List[Dict[str, Any]] = []
        self.proposals_for_b: List[Dict[str, Any]] = []

        # Timestamps
        self.created_at = time.time()
        self.last_sync_at: Optional[float] = None
        self.last_proposal_at: Optional[float] = None

    @property
    def bridge_id(self) -> str:
        return self.contract.id

    @property
    def is_active(self) -> bool:
        return self.contract.state == BridgeState.ACTIVE.value

    def to_dict(self) -> Dict[str, Any]:
        return {
            "bridge_id": self.bridge_id,
            "contract": self.contract.to_dict(),
            "is_active": self.is_active,
            "knowledge_a_available": self.knowledge_a is not None,
            "knowledge_b_available": self.knowledge_b is not None,
            "proposals_for_a": len(self.proposals_for_a),
            "proposals_for_b": len(self.proposals_for_b),
            "firewall_a": self.firewall_a.get_stats(),
            "firewall_b": self.firewall_b.get_stats(),
            "created_at": self.created_at,
            "last_sync_at": self.last_sync_at,
            "last_proposal_at": self.last_proposal_at,
        }


class BridgeRegistry:
    """
    Central registry for all daemon bridges.

    Manages the full lifecycle:
    1. Create bridge (contract + firewalls)
    2. Accept from both sides → activate
    3. Sync structural knowledge through firewalls
    4. Generate proposals via orchestrator
    5. Pause / resume / terminate
    """

    def __init__(
        self,
        event_bus: Optional[EventBus] = None,
        config: Optional[Dict[str, Any]] = None,
    ):
        self._event_bus = event_bus
        self._config = config or {}
        self._contract_manager = ContractManager(event_bus)
        self._extractor = StructuralKnowledgeExtractor(config)
        self._bridges: Dict[str, BridgeInstance] = {}

    def create_bridge(
        self,
        entity_a_id: str,
        entity_b_id: str,
        entity_a_name: str = "",
        entity_b_name: str = "",
        entity_a_shares: Optional[List[str]] = None,
        entity_b_shares: Optional[List[str]] = None,
        ip_ownership: str = "bilateral",
        firewall_config_a: Optional[Dict[str, Any]] = None,
        firewall_config_b: Optional[Dict[str, Any]] = None,
    ) -> BridgeInstance:
        """
        Create a new bridge between two entities.

        Sets up the contract, firewalls for both sides, and registers
        the bridge instance. Does NOT activate — both sides must accept first.

        Args:
            entity_a_id: Unique identifier for entity A.
            entity_b_id: Unique identifier for entity B.
            entity_a_name: Human-readable name for A.
            entity_b_name: Human-readable name for B.
            entity_a_shares: Knowledge categories A will share.
            entity_b_shares: Knowledge categories B will share.
            ip_ownership: IP terms ("bilateral" = each side owns their own).
            firewall_config_a: Custom firewall config for A's side.
            firewall_config_b: Custom firewall config for B's side.

        Returns:
            The created BridgeInstance (PENDING state).
        """
        # Create contract
        contract = self._contract_manager.create_contract(
            entity_a_id=entity_a_id,
            entity_b_id=entity_b_id,
            entity_a_name=entity_a_name,
            entity_b_name=entity_b_name,
            entity_a_shares=entity_a_shares,
            entity_b_shares=entity_b_shares,
            ip_ownership=ip_ownership,
        )

        # Create firewalls for both sides
        firewall_a = IPFirewall(
            entity_id=entity_a_id,
            bridge_id=contract.id,
            event_bus=self._event_bus,
            config=firewall_config_a,
        )
        firewall_b = IPFirewall(
            entity_id=entity_b_id,
            bridge_id=contract.id,
            event_bus=self._event_bus,
            config=firewall_config_b,
        )

        # Create bridge instance
        bridge = BridgeInstance(
            contract=contract,
            firewall_a=firewall_a,
            firewall_b=firewall_b,
        )

        self._bridges[contract.id] = bridge

        logger.info(
            "Bridge created: %s (%s <-> %s)",
            contract.id,
            entity_a_name or entity_a_id[:8],
            entity_b_name or entity_b_id[:8],
        )

        if self._event_bus:
            self._event_bus.publish(Event(
                type=EventType.BRIDGE_CREATED,
                source="bridge.registry",
                data={
                    "bridge_id": contract.id,
                    "entity_a": entity_a_id,
                    "entity_b": entity_b_id,
                },
            ))

        return bridge

    def accept_bridge(
        self,
        bridge_id: str,
        entity_id: str,
    ) -> BridgeInstance:
        """
        Accept a bridge from one entity's side.

        When both sides accept, the bridge activates.
        """
        bridge = self._bridges.get(bridge_id)
        if not bridge:
            raise ValueError(f"Bridge not found: {bridge_id}")

        self._contract_manager.accept_contract(bridge_id, entity_id)
        return bridge

    def sync_knowledge(
        self,
        bridge_id: str,
        entity_id: str,
        routes: Optional[List[Dict[str, Any]]] = None,
        models: Optional[List[Dict[str, Any]]] = None,
        auth_config: Optional[Dict[str, Any]] = None,
        codebase_info: Optional[Dict[str, Any]] = None,
        tech_stack: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Sync structural knowledge from one entity through its firewall.

        The entity's daemon calls this with codebase artifacts. The extractor
        builds StructuralKnowledge, the firewall inspects it, and if it passes,
        it's stored on the bridge.

        Args:
            bridge_id: Which bridge this sync is for.
            entity_id: Which entity is sending knowledge.
            routes/models/auth_config/codebase_info/tech_stack: Codebase data.

        Returns:
            Sync result with stats.
        """
        bridge = self._bridges.get(bridge_id)
        if not bridge:
            raise ValueError(f"Bridge not found: {bridge_id}")

        if not bridge.is_active:
            raise ValueError(f"Bridge {bridge_id} is not active")

        # Build structural knowledge
        knowledge = self._extractor.build_structural_knowledge(
            entity_id=entity_id,
            bridge_id=bridge_id,
            routes=routes,
            models=models,
            auth_config=auth_config,
            codebase_info=codebase_info,
            tech_stack=tech_stack,
        )

        # Select the correct firewall
        if entity_id == bridge.contract.entity_a_id:
            firewall = bridge.firewall_a
        elif entity_id == bridge.contract.entity_b_id:
            firewall = bridge.firewall_b
        else:
            raise ValueError(f"Entity {entity_id} not part of bridge {bridge_id}")

        # Inspect through firewall
        passed, sanitized, blocked_reasons = firewall.inspect_structural_knowledge(
            knowledge, "outbound", self._extractor
        )

        # Store sanitized knowledge
        if entity_id == bridge.contract.entity_a_id:
            bridge.knowledge_a = sanitized
        else:
            bridge.knowledge_b = sanitized

        bridge.last_sync_at = time.time()

        # Publish sync event
        if self._event_bus:
            self._event_bus.publish(Event(
                type=EventType.BRIDGE_KNOWLEDGE_SYNCED,
                source="bridge.registry",
                data={
                    "bridge_id": bridge_id,
                    "entity_id": entity_id,
                    "patterns_synced": len(sanitized.api_patterns) if sanitized else 0,
                    "schemas_synced": len(sanitized.data_schemas) if sanitized else 0,
                    "blocked_count": len(blocked_reasons),
                },
            ))

        result = {
            "bridge_id": bridge_id,
            "entity_id": entity_id,
            "synced": True,
            "all_passed": passed,
            "patterns_synced": len(sanitized.api_patterns) if sanitized else 0,
            "schemas_synced": len(sanitized.data_schemas) if sanitized else 0,
            "auth_flows_synced": len(sanitized.auth_flows) if sanitized else 0,
            "integration_points_synced": len(sanitized.integration_points) if sanitized else 0,
            "blocked_count": len(blocked_reasons),
            "blocked_reasons": blocked_reasons,
        }

        logger.info(
            "Knowledge synced for bridge %s from entity %s: "
            "%d patterns, %d schemas, %d blocked",
            bridge_id, entity_id[:8],
            result["patterns_synced"], result["schemas_synced"],
            result["blocked_count"],
        )

        return result

    def get_bridge(self, bridge_id: str) -> Optional[BridgeInstance]:
        """Get a bridge by ID."""
        return self._bridges.get(bridge_id)

    def list_bridges(
        self,
        entity_id: Optional[str] = None,
        state: Optional[str] = None,
    ) -> List[BridgeInstance]:
        """List bridges, optionally filtered."""
        bridges = list(self._bridges.values())

        if entity_id:
            bridges = [
                b for b in bridges
                if b.contract.entity_a_id == entity_id
                or b.contract.entity_b_id == entity_id
            ]

        if state:
            bridges = [b for b in bridges if b.contract.state == state]

        return bridges

    def get_partners(self, entity_id: str) -> List[Dict[str, str]]:
        """Get all active bridge partners for an entity."""
        partners = []
        for bridge in self._bridges.values():
            if not bridge.is_active:
                continue
            if bridge.contract.entity_a_id == entity_id:
                partners.append({
                    "entity_id": bridge.contract.entity_b_id,
                    "name": bridge.contract.entity_b_name,
                    "bridge_id": bridge.bridge_id,
                })
            elif bridge.contract.entity_b_id == entity_id:
                partners.append({
                    "entity_id": bridge.contract.entity_a_id,
                    "name": bridge.contract.entity_a_name,
                    "bridge_id": bridge.bridge_id,
                })
        return partners

    def pause_bridge(self, bridge_id: str, reason: str = "") -> BridgeInstance:
        """Pause a bridge."""
        bridge = self._bridges.get(bridge_id)
        if not bridge:
            raise ValueError(f"Bridge not found: {bridge_id}")
        self._contract_manager.pause_contract(bridge_id, reason)
        return bridge

    def resume_bridge(self, bridge_id: str) -> BridgeInstance:
        """Resume a paused bridge."""
        bridge = self._bridges.get(bridge_id)
        if not bridge:
            raise ValueError(f"Bridge not found: {bridge_id}")
        self._contract_manager.resume_contract(bridge_id)
        return bridge

    def terminate_bridge(self, bridge_id: str, reason: str = "") -> BridgeInstance:
        """Terminate a bridge permanently."""
        bridge = self._bridges.get(bridge_id)
        if not bridge:
            raise ValueError(f"Bridge not found: {bridge_id}")
        self._contract_manager.terminate_contract(bridge_id, reason)
        return bridge

    def health(self) -> Dict[str, Any]:
        """Bridge registry health and statistics."""
        total = len(self._bridges)
        active = sum(1 for b in self._bridges.values() if b.is_active)
        synced = sum(
            1 for b in self._bridges.values()
            if b.knowledge_a is not None and b.knowledge_b is not None
        )

        return {
            "total_bridges": total,
            "active_bridges": active,
            "fully_synced": synced,
            "possible_cross_bridges": active * (active - 1) // 2 if active > 1 else 0,
        }

    @property
    def bridge_count(self) -> int:
        return len(self._bridges)

    @property
    def active_count(self) -> int:
        return sum(1 for b in self._bridges.values() if b.is_active)

    @property
    def contract_manager(self) -> ContractManager:
        return self._contract_manager

    @property
    def extractor(self) -> StructuralKnowledgeExtractor:
        return self._extractor
