"""
Tests for the UpdatePipeline — autonomous SDK maintenance engine.

Tests cover:
- Data model serialization (FileUpdate, UpdateRecord, etc.)
- PROVIDER_FILE_MAP constant validation
- Change analysis (field_added, field_removed, version_bumped, error_spike)
- Update generation (JSON card, AI code gen, missing files)
- Test execution (no runner, pass, fail)
- Deployment (with and without git)
- Verification (valid JSON card)
- Rollback (success and not-found)
- Full pipeline end-to-end
- Daily cycle scheduling
- Event-driven drift handling
- History persistence

All file I/O uses mock callables — no actual HTTP or disk operations.

MYSTES KYRIOS LLC — Confidential.
"""

import json
import time
import pytest

from anastasia.core.events import EventBus, Event, EventType
from anastasia.knowledge.update_pipeline import (
    FileUpdate,
    UpdateAnalysis,
    TestResult,
    DeployResult,
    UpdateRecord,
    PROVIDER_FILE_MAP,
    UpdatePipeline,
)
from anastasia.knowledge.watchdog import (
    APIWatchdog,
    WatchdogConfig,
    WatchdogReport,
    DetectedChange,
    SchemaSnapshot,
)


# =========================================================================
# Fixtures
# =========================================================================

@pytest.fixture
def event_bus():
    return EventBus()


@pytest.fixture
def watchdog(event_bus, tmp_path):
    return APIWatchdog(
        event_bus=event_bus,
        storage_dir=str(tmp_path / "watchdog"),
    )


@pytest.fixture
def file_store():
    """In-memory file store used by mock file_reader / file_writer."""
    return {}


@pytest.fixture
def file_reader(file_store):
    """Mock file reader that returns content from the in-memory store."""
    def _read(path):
        if path not in file_store:
            raise FileNotFoundError(f"No such file: {path}")
        return file_store[path]
    return _read


@pytest.fixture
def file_writer(file_store):
    """Mock file writer that stores content in the in-memory store."""
    def _write(path, content):
        file_store[path] = content
        return True
    return _write


@pytest.fixture
def git_commits():
    """Accumulator for git commit calls."""
    return []


@pytest.fixture
def git_commit(git_commits):
    """Mock git commit callable that returns a fake SHA."""
    def _commit(message, files):
        sha = f"abc{len(git_commits):04d}"
        git_commits.append({"message": message, "files": files, "sha": sha})
        return sha
    return _commit


@pytest.fixture
def passing_test_runner():
    """Mock test runner that always passes."""
    def _run(command):
        return {"exit_code": 0, "tests_run": 10, "tests_passed": 10,
                "tests_failed": 0, "stdout": "All passed", "stderr": "",
                "duration_ms": 150}
    return _run


@pytest.fixture
def failing_test_runner():
    """Mock test runner that always fails."""
    def _run(command):
        return {"exit_code": 1, "tests_run": 10, "tests_passed": 7,
                "tests_failed": 3, "stdout": "", "stderr": "3 failures",
                "duration_ms": 200}
    return _run


@pytest.fixture
def mock_ai():
    """Mock AI callable that returns predictable code."""
    def _generate(prompt):
        return "# updated code generated by mock AI\nprint('updated')\n"
    return _generate


@pytest.fixture
def sample_card_json():
    """Sample JSON knowledge card for testing."""
    return json.dumps({
        "module_id": "test",
        "name": "Test",
        "version": "1.0",
        "last_updated": "2026-01-01",
        "strengths": [],
        "learned_from": [],
    })


@pytest.fixture
def pipeline(event_bus, watchdog, tmp_path, file_reader, file_writer):
    """Basic pipeline with mock I/O but no AI, no test runner, no git."""
    return UpdatePipeline(
        event_bus=event_bus,
        watchdog=watchdog,
        storage_dir=str(tmp_path / "updates"),
        file_reader=file_reader,
        file_writer=file_writer,
    )


def _make_report(provider_id, changes):
    """Helper to create a WatchdogReport with given changes."""
    report = WatchdogReport(provider_id=provider_id)
    report.changes_detected = changes
    return report


# =========================================================================
# 1. test_file_update_to_dict
# =========================================================================

class TestFileUpdateToDict:
    def test_file_update_to_dict(self):
        fu = FileUpdate(
            file_path="picasso/client.py",
            update_type="modify",
            old_content="old code",
            new_content="new code here!",
            diff_summary="Updated response parser",
            reason="field_added in response",
        )
        d = fu.to_dict()
        assert d["file_path"] == "picasso/client.py"
        assert d["update_type"] == "modify"
        assert d["diff_summary"] == "Updated response parser"
        assert d["reason"] == "field_added in response"
        assert d["content_length"] == len("new code here!")
        # old_content and new_content should NOT leak into the dict
        assert "old_content" not in d
        assert "new_content" not in d


# =========================================================================
# 2. test_update_record_to_dict
# =========================================================================

class TestUpdateRecordToDict:
    def test_update_record_to_dict(self):
        analysis = UpdateAnalysis(
            provider_id="picasso_redbox",
            changes=[DetectedChange(
                change_type="field_added",
                severity="additive",
                description="New field: loyalty_tier",
            )],
            affected_files={"picasso/client.py": "update parser"},
            breaking=False,
            ai_summary="A new field was added.",
        )
        file_update = FileUpdate(
            file_path="picasso/client.py",
            update_type="modify",
            new_content="updated",
            diff_summary="Update parser",
        )
        test_result = TestResult(passed=True, tests_run=5, tests_passed=5)
        deploy_result = DeployResult(success=True, commit_sha="abc1234",
                                     files_updated=1)

        record = UpdateRecord(
            update_id="rec-001",
            provider_id="picasso_redbox",
            status="verified",
            analysis=analysis,
            file_updates=[file_update],
            test_result=test_result,
            deploy_result=deploy_result,
            verified=True,
            rollback_available=True,
        )
        d = record.to_dict()
        assert d["update_id"] == "rec-001"
        assert d["provider_id"] == "picasso_redbox"
        assert d["status"] == "verified"
        assert d["analysis"]["changes_count"] == 1
        assert d["analysis"]["affected_files"] == {"picasso/client.py": "update parser"}
        assert len(d["files_changed"]) == 1
        assert d["files_changed"][0]["file_path"] == "picasso/client.py"
        assert d["test_result"]["passed"] is True
        assert d["deploy_result"]["commit_sha"] == "abc1234"
        assert d["verified"] is True
        assert d["rollback_available"] is True


# =========================================================================
# 3. test_provider_file_map_entries
# =========================================================================

class TestProviderFileMap:
    def test_provider_file_map_entries(self):
        expected_providers = [
            "picasso_redbox",
            "duffel_ndc",
            "kiwi_tequila",
            "airgateway_ndc",
            "mystifly",
            "travelfusion",
            "tripstack",
            "liteapi_hotels",
        ]
        for provider_id in expected_providers:
            assert provider_id in PROVIDER_FILE_MAP, (
                f"{provider_id} missing from PROVIDER_FILE_MAP"
            )
            # Every provider must have at least a card
            assert "card" in PROVIDER_FILE_MAP[provider_id]


# =========================================================================
# 4. test_analyze_field_added
# =========================================================================

class TestAnalyzeFieldAdded:
    def test_analyze_field_added(self, pipeline):
        change = DetectedChange(
            change_type="field_added",
            severity="additive",
            description="New field: loyalty_tier",
            evidence={"field": "loyalty_tier"},
        )
        report = _make_report("picasso_redbox", [change])
        analysis = pipeline.analyze_changes(report)

        assert analysis.provider_id == "picasso_redbox"
        assert not analysis.breaking
        # field_added should map to both client and card
        assert "picasso/client.py" in analysis.affected_files
        assert "anastasia/modules/cards/picasso_redbox.json" in analysis.affected_files


# =========================================================================
# 5. test_analyze_field_removed
# =========================================================================

class TestAnalyzeFieldRemoved:
    def test_analyze_field_removed(self, pipeline):
        change = DetectedChange(
            change_type="field_removed",
            severity="breaking",
            description="Field removed: baggage_allowance",
        )
        report = _make_report("picasso_redbox", [change])
        analysis = pipeline.analyze_changes(report)

        assert analysis.breaking is True
        assert "picasso/client.py" in analysis.affected_files
        assert "anastasia/modules/cards/picasso_redbox.json" in analysis.affected_files


# =========================================================================
# 6. test_analyze_version_bumped
# =========================================================================

class TestAnalyzeVersionBumped:
    def test_analyze_version_bumped(self, pipeline):
        change = DetectedChange(
            change_type="version_bumped",
            severity="additive",
            description="API version changed: 2.3 -> 2.4",
            evidence={"old": "2.3", "new": "2.4"},
        )
        report = _make_report("picasso_redbox", [change])
        analysis = pipeline.analyze_changes(report)

        # version_bumped should only map to the card, not the client
        assert "anastasia/modules/cards/picasso_redbox.json" in analysis.affected_files
        assert "picasso/client.py" not in analysis.affected_files


# =========================================================================
# 7. test_analyze_error_spike
# =========================================================================

class TestAnalyzeErrorSpike:
    def test_analyze_error_spike(self, pipeline):
        change = DetectedChange(
            change_type="error_rate_spike",
            severity="breaking",
            description="Error rate spike: 5 failures in 300s",
            evidence={"error_count": 5, "window_sec": 300},
        )
        report = _make_report("picasso_redbox", [change])
        analysis = pipeline.analyze_changes(report)

        # error_rate_spike should only affect the client
        assert "picasso/client.py" in analysis.affected_files
        # Card should NOT be touched for error spikes
        assert "anastasia/modules/cards/picasso_redbox.json" not in analysis.affected_files


# =========================================================================
# 8. test_generate_json_card_update
# =========================================================================

class TestGenerateJsonCardUpdate:
    def test_generate_json_card_update(self, pipeline, file_store, sample_card_json):
        card_path = "anastasia/modules/cards/picasso_redbox.json"
        file_store[card_path] = sample_card_json

        change = DetectedChange(
            change_type="field_added",
            severity="additive",
            description="New field: loyalty_tier",
            evidence={"field": "loyalty_tier"},
        )
        analysis = UpdateAnalysis(
            provider_id="picasso_redbox",
            changes=[change],
            affected_files={card_path: "Update knowledge card"},
        )
        updates = pipeline.generate_updates(analysis)

        assert len(updates) == 1
        assert updates[0].file_path == card_path
        new_card = json.loads(updates[0].new_content)
        # last_updated should be today
        assert new_card["last_updated"] == time.strftime("%Y-%m-%d")
        # strength note for the new field should be added
        assert any("loyalty_tier" in s for s in new_card["strengths"])


# =========================================================================
# 9. test_generate_code_update_with_ai
# =========================================================================

class TestGenerateCodeUpdateWithAI:
    def test_generate_code_update_with_ai(self, event_bus, watchdog, tmp_path,
                                          file_store, file_reader, file_writer,
                                          mock_ai):
        file_store["picasso/client.py"] = "# original client code\n"

        pipe = UpdatePipeline(
            event_bus=event_bus,
            watchdog=watchdog,
            storage_dir=str(tmp_path / "updates"),
            ai_generate=mock_ai,
            file_reader=file_reader,
            file_writer=file_writer,
        )
        change = DetectedChange(
            change_type="field_added",
            severity="additive",
            description="New field",
        )
        analysis = UpdateAnalysis(
            provider_id="picasso_redbox",
            changes=[change],
            affected_files={"picasso/client.py": "Update parser"},
        )
        updates = pipe.generate_updates(analysis)

        assert len(updates) == 1
        assert updates[0].file_path == "picasso/client.py"
        assert "updated" in updates[0].new_content


# =========================================================================
# 10. test_generate_skips_missing_files
# =========================================================================

class TestGenerateSkipsMissingFiles:
    def test_generate_skips_missing_files(self, pipeline):
        """Files that don't exist in the store should be skipped gracefully."""
        change = DetectedChange(
            change_type="field_added",
            severity="additive",
            description="New field",
        )
        analysis = UpdateAnalysis(
            provider_id="picasso_redbox",
            changes=[change],
            affected_files={"nonexistent/file.py": "Update something"},
        )
        updates = pipeline.generate_updates(analysis)
        assert updates == []


# =========================================================================
# 11. test_test_updates_no_runner
# =========================================================================

class TestTestUpdatesNoRunner:
    def test_test_updates_no_runner(self, pipeline):
        """With no test runner configured, tests should auto-pass."""
        updates = [
            FileUpdate(file_path="a.py", update_type="modify",
                       new_content="code"),
        ]
        result = pipeline.test_updates(updates)
        assert result.passed is True
        assert result.tests_run == 0


# =========================================================================
# 12. test_test_updates_pass
# =========================================================================

class TestTestUpdatesPass:
    def test_test_updates_pass(self, event_bus, watchdog, tmp_path,
                               file_reader, file_writer, passing_test_runner):
        pipe = UpdatePipeline(
            event_bus=event_bus,
            watchdog=watchdog,
            storage_dir=str(tmp_path / "updates"),
            run_tests=passing_test_runner,
            file_reader=file_reader,
            file_writer=file_writer,
        )
        updates = [
            FileUpdate(file_path="a.py", update_type="modify",
                       new_content="code"),
        ]
        result = pipe.test_updates(updates)
        assert result.passed is True
        assert result.tests_run == 10
        assert result.tests_passed == 10
        assert result.tests_failed == 0


# =========================================================================
# 13. test_test_updates_fail
# =========================================================================

class TestTestUpdatesFail:
    def test_test_updates_fail(self, event_bus, watchdog, tmp_path,
                               file_reader, file_writer, failing_test_runner):
        pipe = UpdatePipeline(
            event_bus=event_bus,
            watchdog=watchdog,
            storage_dir=str(tmp_path / "updates"),
            run_tests=failing_test_runner,
            file_reader=file_reader,
            file_writer=file_writer,
        )
        updates = [
            FileUpdate(file_path="a.py", update_type="modify",
                       new_content="bad code"),
        ]
        result = pipe.test_updates(updates)
        assert result.passed is False
        assert result.tests_failed == 3


# =========================================================================
# 14. test_deploy_updates_no_git
# =========================================================================

class TestDeployUpdatesNoGit:
    def test_deploy_updates_no_git(self, pipeline, file_store):
        """Deploy without git should still succeed — files are written."""
        file_store["a.py"] = "new code"
        updates = [
            FileUpdate(file_path="a.py", update_type="modify",
                       old_content="old", new_content="new code"),
        ]
        result = pipeline.deploy_updates(updates, "picasso_redbox")
        assert result.success is True
        assert result.files_updated == 1
        assert result.commit_sha == ""


# =========================================================================
# 15. test_deploy_updates_with_git
# =========================================================================

class TestDeployUpdatesWithGit:
    def test_deploy_updates_with_git(self, event_bus, watchdog, tmp_path,
                                     file_reader, file_writer, git_commit,
                                     git_commits, file_store):
        file_store["client.py"] = "updated"
        pipe = UpdatePipeline(
            event_bus=event_bus,
            watchdog=watchdog,
            storage_dir=str(tmp_path / "updates"),
            file_reader=file_reader,
            file_writer=file_writer,
            git_commit=git_commit,
        )
        updates = [
            FileUpdate(file_path="client.py", update_type="modify",
                       old_content="old", new_content="updated"),
        ]
        result = pipe.deploy_updates(updates, "picasso_redbox")
        assert result.success is True
        assert result.commit_sha.startswith("abc")
        assert len(git_commits) == 1
        assert "picasso_redbox" in git_commits[0]["message"]
        assert "client.py" in git_commits[0]["files"]


# =========================================================================
# 16. test_verify_deployment_valid_json
# =========================================================================

class TestVerifyDeploymentValidJson:
    def test_verify_deployment_valid_json(self, pipeline, file_store, watchdog,
                                         sample_card_json):
        card_path = PROVIDER_FILE_MAP["picasso_redbox"]["card"]
        file_store[card_path] = sample_card_json

        # Register provider so get_provider_status returns something
        watchdog.register_provider(WatchdogConfig(provider_id="picasso_redbox"))

        verified = pipeline.verify_deployment("picasso_redbox")
        assert verified is True

    def test_verify_deployment_invalid_json(self, pipeline, file_store, watchdog):
        card_path = PROVIDER_FILE_MAP["picasso_redbox"]["card"]
        file_store[card_path] = "NOT VALID JSON {{{"

        watchdog.register_provider(WatchdogConfig(provider_id="picasso_redbox"))

        verified = pipeline.verify_deployment("picasso_redbox")
        assert verified is False


# =========================================================================
# 17. test_rollback_success
# =========================================================================

class TestRollbackSuccess:
    def test_rollback_success(self, event_bus, watchdog, tmp_path,
                              file_store, file_reader, file_writer):
        pipe = UpdatePipeline(
            event_bus=event_bus,
            watchdog=watchdog,
            storage_dir=str(tmp_path / "updates"),
            file_reader=file_reader,
            file_writer=file_writer,
        )
        # Manually add a record with rollback data
        record = UpdateRecord(
            update_id="rb-001",
            provider_id="picasso_redbox",
            status="verified",
            rollback_available=True,
            file_updates=[
                FileUpdate(
                    file_path="client.py",
                    update_type="modify",
                    old_content="original code",
                    new_content="new code",
                ),
            ],
        )
        pipe._history.append(record)
        file_store["client.py"] = "new code"

        # Track events
        events = []
        event_bus.subscribe(EventType.API_UPDATE_ROLLED_BACK,
                            lambda e: events.append(e))

        success = pipe.rollback("rb-001")
        assert success is True
        assert file_store["client.py"] == "original code"
        assert record.status == "rolled_back"
        assert len(events) == 1
        assert events[0].data["update_id"] == "rb-001"


# =========================================================================
# 18. test_rollback_not_found
# =========================================================================

class TestRollbackNotFound:
    def test_rollback_not_found(self, pipeline):
        result = pipeline.rollback("nonexistent-id")
        assert result is False


# =========================================================================
# 19. test_process_update_full_pipeline
# =========================================================================

class TestProcessUpdateFullPipeline:
    def test_process_update_full_pipeline(self, event_bus, watchdog, tmp_path,
                                         file_store, file_reader, file_writer,
                                         sample_card_json):
        card_path = PROVIDER_FILE_MAP["picasso_redbox"]["card"]
        file_store[card_path] = sample_card_json

        # Register provider for verify step
        watchdog.register_provider(WatchdogConfig(provider_id="picasso_redbox"))

        pipe = UpdatePipeline(
            event_bus=event_bus,
            watchdog=watchdog,
            storage_dir=str(tmp_path / "updates"),
            file_reader=file_reader,
            file_writer=file_writer,
        )

        # Capture events
        event_types = []
        event_bus.subscribe_all(lambda e: event_types.append(e.type))

        change = DetectedChange(
            change_type="field_added",
            severity="additive",
            description="New field: loyalty_tier",
            evidence={"field": "loyalty_tier"},
        )
        report = _make_report("picasso_redbox", [change])
        record = pipe.process_update(report)

        assert record.status == "verified"
        assert record.provider_id == "picasso_redbox"
        assert record.analysis is not None
        assert len(record.file_updates) > 0
        assert record.test_result is not None
        assert record.test_result.passed is True
        assert record.deploy_result is not None
        assert record.deploy_result.success is True
        assert record.verified is True
        assert record.completed_at is not None

        # Verify the card was actually updated in the file store
        updated_card = json.loads(file_store[card_path])
        assert updated_card["last_updated"] == time.strftime("%Y-%m-%d")

        # Verify event chain
        assert EventType.API_UPDATE_STARTED in event_types
        assert EventType.API_UPDATE_GENERATED in event_types
        assert EventType.API_UPDATE_TESTED in event_types
        assert EventType.API_UPDATE_DEPLOYED in event_types
        assert EventType.API_UPDATE_VERIFIED in event_types


# =========================================================================
# 20. test_daily_cycle_no_changes
# =========================================================================

class TestDailyCycleNoChanges:
    def test_daily_cycle_no_changes(self, event_bus, watchdog, tmp_path,
                                    file_reader, file_writer):
        """When watchdog reports no drift, daily cycle should produce no updates."""
        watchdog.register_provider(WatchdogConfig(provider_id="picasso_redbox"))

        pipe = UpdatePipeline(
            event_bus=event_bus,
            watchdog=watchdog,
            storage_dir=str(tmp_path / "updates"),
            file_reader=file_reader,
            file_writer=file_writer,
        )
        results = pipe.run_daily_cycle()
        # No HTTP probe, no changelog, no errors -> no changes detected
        assert results == {}


# =========================================================================
# 21. test_on_drift_detected_event
# =========================================================================

class TestOnDriftDetectedEvent:
    def test_on_drift_detected_event(self, event_bus, watchdog, tmp_path,
                                     file_store, file_reader, file_writer,
                                     sample_card_json):
        card_path = PROVIDER_FILE_MAP["picasso_redbox"]["card"]
        file_store[card_path] = sample_card_json

        watchdog.register_provider(WatchdogConfig(provider_id="picasso_redbox"))

        pipe = UpdatePipeline(
            event_bus=event_bus,
            watchdog=watchdog,
            storage_dir=str(tmp_path / "updates"),
            file_reader=file_reader,
            file_writer=file_writer,
        )

        # Simulate drift event from watchdog
        event_bus.publish(Event(
            type=EventType.API_DRIFT_DETECTED,
            source="watchdog",
            data={
                "provider_id": "picasso_redbox",
                "severity": "additive",
                "changes_count": 1,
                "report": {
                    "provider_id": "picasso_redbox",
                    "checked_at": time.time(),
                    "changes": [
                        {
                            "change_type": "field_added",
                            "severity": "additive",
                            "description": "New field: loyalty_tier",
                            "affected_files": [],
                            "evidence": {"field": "loyalty_tier"},
                        },
                    ],
                },
            },
        ))

        # The pipeline should have processed the update
        assert len(pipe._history) > 0
        latest = pipe._history[-1]
        assert latest.provider_id == "picasso_redbox"
        assert latest.status in ("verified", "deployed")


# =========================================================================
# 22. test_history_persistence
# =========================================================================

class TestHistoryPersistence:
    def test_history_persistence(self, event_bus, watchdog, tmp_path,
                                 file_store, file_reader, file_writer,
                                 sample_card_json):
        card_path = PROVIDER_FILE_MAP["picasso_redbox"]["card"]
        file_store[card_path] = sample_card_json

        watchdog.register_provider(WatchdogConfig(provider_id="picasso_redbox"))

        storage_dir = str(tmp_path / "updates")

        pipe = UpdatePipeline(
            event_bus=event_bus,
            watchdog=watchdog,
            storage_dir=storage_dir,
            file_reader=file_reader,
            file_writer=file_writer,
        )

        change = DetectedChange(
            change_type="version_bumped",
            severity="additive",
            description="API version changed: 1.0 -> 1.1",
            evidence={"old": "1.0", "new": "1.1"},
        )
        report = _make_report("picasso_redbox", [change])
        pipe.process_update(report)

        # History should be saved to disk
        history_path = tmp_path / "updates" / "history.json"
        assert history_path.exists()

        saved_data = json.loads(history_path.read_text(encoding="utf-8"))
        assert len(saved_data) > 0
        assert saved_data[-1]["provider_id"] == "picasso_redbox"

        # get_update_history should return dicts
        history = pipe.get_update_history(provider_id="picasso_redbox")
        assert len(history) > 0
        assert history[-1]["provider_id"] == "picasso_redbox"

        # get_record should return single record
        update_id = pipe._history[-1].update_id
        record_dict = pipe.get_record(update_id)
        assert record_dict is not None
        assert record_dict["update_id"] == update_id

        # get_record for unknown ID returns None
        assert pipe.get_record("nonexistent") is None

        # get_pending_updates should be empty (everything completed)
        pending = pipe.get_pending_updates()
        assert len(pending) == 0
