"""Add multi-leg support to Deal model

Revision ID: 79966bdfccc1
Revises: 0b058043b7dd
Create Date: 2026-01-28 11:14:59.769228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79966bdfccc1'
down_revision = '0b058043b7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_multi_leg', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('flight_legs', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('total_legs', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_column('total_legs')
        batch_op.drop_column('flight_legs')
        batch_op.drop_column('is_multi_leg')

    # ### end Alembic commands ###
