"""
Code Generator — Produces native integration code in the customer's language.

Given a detected TechStack and a SystemProfile (what the customer is connecting
to), generates ready-to-use integration files: API client, payment adapter,
booking route handler, search UI component, and configuration.

Every generated file is wrapped in an ActionProposal for admin approval —
ANASTASiA never writes to a customer's codebase without human sign-off.

MYSTES KYRIOS LLC — Confidential.
"""

import logging
import time
import uuid
from typing import Any, Dict, List, Optional

from ..core.events import EventBus, Event, EventType
from ..core.types import (
    SystemProfile,
    TechStack,
    ActionProposal,
    AdapterPattern,
    BookingFlow,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Code templates — realistic, production-quality snippets
# ---------------------------------------------------------------------------

# --- Python / Flask templates ---

PYTHON_FLASK_API_CLIENT = '''\
"""
ANASTASiA API Client — Auto-generated for {system_name}.

Handles authentication, search, booking, and error recovery
against the {system_name} API via ANASTASiA\'s proxy layer.

Generated by ANASTASiA Integrator v1.0
"""

import logging
import os
import time
from typing import Any, Dict, List, Optional

import requests

logger = logging.getLogger(__name__)


class ANASTASiAClient:
    """Client for ANASTASiA-mediated {system_name} API access."""

    DEFAULT_BASE_URL = "https://api.anastasia.mystes.app/v1"
    DEFAULT_TIMEOUT = 30

    def __init__(
        self,
        api_key: Optional[str] = None,
        agency_id: Optional[str] = None,
        base_url: Optional[str] = None,
    ):
        self.api_key = api_key or os.environ.get("ANASTASIA_API_KEY", "")
        self.agency_id = agency_id or os.environ.get("ANASTASIA_AGENCY_ID", "")
        self.base_url = (base_url or os.environ.get(
            "ANASTASIA_BASE_URL", self.DEFAULT_BASE_URL
        )).rstrip("/")
        self._session = requests.Session()
        self._session.headers.update({{
            "Authorization": f"Bearer {{self.api_key}}",
            "X-Agency-ID": self.agency_id,
            "Content-Type": "application/json",
            "User-Agent": "ANASTASiA-Client/1.0 (Python/Flask)",
        }})

    def search_flights(
        self,
        origin: str,
        destination: str,
        departure_date: str,
        return_date: Optional[str] = None,
        adults: int = 1,
        cabin_class: str = "ECONOMY",
    ) -> Dict[str, Any]:
        """
        Search for flights with geographic price arbitrage.

        Returns results with home_price, arbitrage_price, and savings.
        """
        payload = {{
            "origin": origin,
            "destination": destination,
            "departure_date": departure_date,
            "return_date": return_date,
            "adults": adults,
            "cabin_class": cabin_class,
            "vertical": "flights",
        }}
        return self._post("/search", payload)

    def search_hotels(
        self,
        city: str,
        country_code: str,
        check_in: str,
        check_out: str,
        guests: int = 2,
        rooms: int = 1,
    ) -> Dict[str, Any]:
        """Search for hotels via ANASTASiA."""
        payload = {{
            "city": city,
            "country_code": country_code,
            "check_in": check_in,
            "check_out": check_out,
            "guests": guests,
            "rooms": rooms,
            "vertical": "hotels",
        }}
        return self._post("/search", payload)

    def get_deal(self, deal_id: str) -> Dict[str, Any]:
        """Retrieve a specific deal by ID."""
        return self._get(f"/deals/{{deal_id}}")

    def create_booking(
        self,
        deal_id: str,
        passenger_details: List[Dict[str, str]],
        payment_token: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Create a booking for an approved deal.

        Payment is handled through your existing {payment_processor} integration.
        ANASTASiA charges the platform fee separately.
        """
        payload = {{
            "deal_id": deal_id,
            "passengers": passenger_details,
            "payment_token": payment_token,
        }}
        return self._post("/bookings", payload)

    def get_booking_status(self, booking_id: str) -> Dict[str, Any]:
        """Check booking status."""
        return self._get(f"/bookings/{{booking_id}}")

    def _get(self, path: str) -> Dict[str, Any]:
        """Execute a GET request."""
        url = f"{{self.base_url}}{{path}}"
        try:
            resp = self._session.get(url, timeout=self.DEFAULT_TIMEOUT)
            resp.raise_for_status()
            return resp.json()
        except requests.RequestException as e:
            logger.error("ANASTASiA API GET %s failed: %s", path, e)
            raise

    def _post(self, path: str, data: Dict[str, Any]) -> Dict[str, Any]:
        """Execute a POST request."""
        url = f"{{self.base_url}}{{path}}"
        try:
            resp = self._session.post(url, json=data, timeout=self.DEFAULT_TIMEOUT)
            resp.raise_for_status()
            return resp.json()
        except requests.RequestException as e:
            logger.error("ANASTASiA API POST %s failed: %s", path, e)
            raise
'''

PYTHON_FLASK_PAYMENT_ADAPTER = '''\
"""
ANASTASiA Payment Adapter — Bridges {payment_processor} to ANASTASiA fee collection.

Intercepts your existing payment flow to split the ANASTASiA platform fee
from the supplier cost. Your customer pays one total; this adapter handles
the split behind the scenes.

Generated by ANASTASiA Integrator v1.0
"""

import logging
import os
from typing import Any, Dict, Optional

{payment_import}

logger = logging.getLogger(__name__)


class ANASTASiAPaymentAdapter:
    """
    Adapter between your {payment_processor} integration and ANASTASiA fees.

    Flow:
    1. Customer selects a deal (arbitrage price + platform fee = total)
    2. You charge the total via {payment_processor}
    3. This adapter reports the fee portion to ANASTASiA for reconciliation
    4. ANASTASiA collects its fee via your connected Stripe account
    """

    def __init__(self, anastasia_client, {payment_processor}_client=None):
        self.anastasia = anastasia_client
        self.{payment_processor} = {payment_processor}_client

    def calculate_total(self, deal: Dict[str, Any]) -> Dict[str, Any]:
        """
        Calculate the total charge for a deal.

        Returns breakdown of supplier cost, platform fee, and total.
        """
        arbitrage_price = deal.get("arbitrage_price", 0)
        platform_fee = deal.get("platform_fee_usd", 0)
        total = arbitrage_price + platform_fee

        return {{
            "supplier_cost": arbitrage_price,
            "platform_fee": platform_fee,
            "total_charge": total,
            "currency": deal.get("currency", "USD"),
            "savings_vs_retail": deal.get("gross_savings", 0),
        }}

    def process_payment(
        self,
        deal_id: str,
        amount_cents: int,
        payment_method_id: str,
        customer_email: str,
        metadata: Optional[Dict[str, str]] = None,
    ) -> Dict[str, Any]:
        """
        Process payment and report to ANASTASiA.

        Args:
            deal_id: ANASTASiA deal identifier.
            amount_cents: Total amount in cents.
            payment_method_id: {payment_processor} payment method.
            customer_email: Customer email for receipt.
            metadata: Additional metadata for the payment.

        Returns:
            Payment result with booking confirmation.
        """
        # Step 1: Charge via {payment_processor}
        payment_result = self._charge_{payment_processor}(
            amount_cents=amount_cents,
            payment_method_id=payment_method_id,
            customer_email=customer_email,
            metadata={{
                "deal_id": deal_id,
                "source": "anastasia",
                **(metadata or {{}}),
            }},
        )

        # Step 2: Report to ANASTASiA for fee reconciliation
        if payment_result.get("success"):
            self.anastasia._post("/payments/report", {{
                "deal_id": deal_id,
                "payment_id": payment_result.get("payment_id"),
                "amount_cents": amount_cents,
                "processor": "{payment_processor}",
            }})

        return payment_result

    def _charge_{payment_processor}(self, **kwargs) -> Dict[str, Any]:
        """Execute the actual {payment_processor} charge."""
        # This integrates with your existing {payment_processor} setup
        raise NotImplementedError(
            "Wire this to your existing {payment_processor} charge logic"
        )
'''

PYTHON_FLASK_BOOKING_ROUTE = '''\
"""
ANASTASiA Booking Routes — Flask blueprint for deal search and booking.

Plug this blueprint into your Flask app to add ANASTASiA-powered
flight and hotel search with geographic price arbitrage.

Generated by ANASTASiA Integrator v1.0
"""

import logging
from functools import wraps
from typing import Optional

from flask import Blueprint, jsonify, request, session

logger = logging.getLogger(__name__)

# Import the generated client and payment adapter
from .anastasia_client import ANASTASiAClient
from .anastasia_payment import ANASTASiAPaymentAdapter

anastasia_bp = Blueprint("anastasia", __name__, url_prefix="/anastasia")

# Initialize client (configure via environment variables)
client = ANASTASiAClient()


def require_auth(f):
    """Decorator to require authentication for booking routes."""
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get("user_id"):
            return jsonify({{"error": "Authentication required"}}), 401
        return f(*args, **kwargs)
    return decorated


@anastasia_bp.route("/search", methods=["POST"])
def search():
    """
    Search for deals with geographic price arbitrage.

    POST /anastasia/search
    Body: {{
        "origin": "JFK",
        "destination": "LHR",
        "departure_date": "2026-06-15",
        "return_date": "2026-06-22",  // optional
        "adults": 1,
        "cabin_class": "ECONOMY",
        "vertical": "flights"  // or "hotels"
    }}
    """
    data = request.get_json()
    if not data:
        return jsonify({{"error": "Request body required"}}), 400

    vertical = data.get("vertical", "flights")

    try:
        if vertical == "flights":
            results = client.search_flights(
                origin=data.get("origin", ""),
                destination=data.get("destination", ""),
                departure_date=data.get("departure_date", ""),
                return_date=data.get("return_date"),
                adults=data.get("adults", 1),
                cabin_class=data.get("cabin_class", "ECONOMY"),
            )
        elif vertical == "hotels":
            results = client.search_hotels(
                city=data.get("city", ""),
                country_code=data.get("country_code", ""),
                check_in=data.get("check_in", ""),
                check_out=data.get("check_out", ""),
                guests=data.get("guests", 2),
                rooms=data.get("rooms", 1),
            )
        else:
            return jsonify({{"error": f"Unknown vertical: {{vertical}}"}}), 400

        return jsonify(results)

    except Exception as e:
        logger.error("ANASTASiA search failed: %s", e)
        return jsonify({{"error": "Search temporarily unavailable"}}), 503


@anastasia_bp.route("/deals/<deal_id>", methods=["GET"])
def get_deal(deal_id: str):
    """Retrieve a specific deal."""
    try:
        deal = client.get_deal(deal_id)
        return jsonify(deal)
    except Exception as e:
        logger.error("Failed to get deal %s: %s", deal_id, e)
        return jsonify({{"error": "Deal not found"}}), 404


@anastasia_bp.route("/book", methods=["POST"])
@require_auth
def book():
    """
    Book a deal.

    POST /anastasia/book
    Body: {{
        "deal_id": "...",
        "passengers": [
            {{"first_name": "...", "last_name": "...", "dob": "...", "email": "..."}}
        ],
        "payment_token": "..."
    }}
    """
    data = request.get_json()
    if not data or not data.get("deal_id"):
        return jsonify({{"error": "deal_id required"}}), 400

    try:
        booking = client.create_booking(
            deal_id=data["deal_id"],
            passenger_details=data.get("passengers", []),
            payment_token=data.get("payment_token"),
        )
        return jsonify(booking), 201

    except Exception as e:
        logger.error("Booking failed: %s", e)
        return jsonify({{"error": "Booking failed"}}), 500


@anastasia_bp.route("/bookings/<booking_id>", methods=["GET"])
@require_auth
def booking_status(booking_id: str):
    """Check booking status."""
    try:
        status = client.get_booking_status(booking_id)
        return jsonify(status)
    except Exception as e:
        logger.error("Status check failed for %s: %s", booking_id, e)
        return jsonify({{"error": "Booking not found"}}), 404
'''

# --- JavaScript / Express templates ---

JS_EXPRESS_API_CLIENT = '''\
/**
 * ANASTASiA API Client — Auto-generated for {system_name}.
 *
 * Handles authentication, search, booking, and error recovery
 * against the {system_name} API via ANASTASiA\'s proxy layer.
 *
 * Generated by ANASTASiA Integrator v1.0
 */

const axios = require('axios');

class ANASTASiAClient {{
  constructor(options = {{}}) {{
    this.apiKey = options.apiKey || process.env.ANASTASIA_API_KEY || '';
    this.agencyId = options.agencyId || process.env.ANASTASIA_AGENCY_ID || '';
    this.baseURL = (options.baseURL || process.env.ANASTASIA_BASE_URL ||
                    'https://api.anastasia.mystes.app/v1').replace(/\\/$/, '');

    this.http = axios.create({{
      baseURL: this.baseURL,
      timeout: 30000,
      headers: {{
        'Authorization': `Bearer ${{this.apiKey}}`,
        'X-Agency-ID': this.agencyId,
        'Content-Type': 'application/json',
        'User-Agent': 'ANASTASiA-Client/1.0 (Node.js/Express)',
      }},
    }});
  }}

  /**
   * Search for flights with geographic price arbitrage.
   */
  async searchFlights({{ origin, destination, departureDate, returnDate, adults = 1, cabinClass = 'ECONOMY' }}) {{
    const {{ data }} = await this.http.post('/search', {{
      origin,
      destination,
      departure_date: departureDate,
      return_date: returnDate,
      adults,
      cabin_class: cabinClass,
      vertical: 'flights',
    }});
    return data;
  }}

  /**
   * Search for hotels via ANASTASiA.
   */
  async searchHotels({{ city, countryCode, checkIn, checkOut, guests = 2, rooms = 1 }}) {{
    const {{ data }} = await this.http.post('/search', {{
      city,
      country_code: countryCode,
      check_in: checkIn,
      check_out: checkOut,
      guests,
      rooms,
      vertical: 'hotels',
    }});
    return data;
  }}

  /**
   * Retrieve a specific deal by ID.
   */
  async getDeal(dealId) {{
    const {{ data }} = await this.http.get(`/deals/${{dealId}}`);
    return data;
  }}

  /**
   * Create a booking for an approved deal.
   */
  async createBooking({{ dealId, passengers, paymentToken }}) {{
    const {{ data }} = await this.http.post('/bookings', {{
      deal_id: dealId,
      passengers,
      payment_token: paymentToken,
    }});
    return data;
  }}

  /**
   * Check booking status.
   */
  async getBookingStatus(bookingId) {{
    const {{ data }} = await this.http.get(`/bookings/${{bookingId}}`);
    return data;
  }}
}}

module.exports = ANASTASiAClient;
'''

JS_EXPRESS_PAYMENT_ADAPTER = '''\
/**
 * ANASTASiA Payment Adapter — Bridges {payment_processor} to ANASTASiA fees.
 *
 * Generated by ANASTASiA Integrator v1.0
 */

class ANASTASiAPaymentAdapter {{
  constructor(anastasiaClient, paymentClient) {{
    this.anastasia = anastasiaClient;
    this.payment = paymentClient;
  }}

  /**
   * Calculate total charge breakdown for a deal.
   */
  calculateTotal(deal) {{
    const arbitragePrice = deal.arbitrage_price || 0;
    const platformFee = deal.platform_fee_usd || 0;
    return {{
      supplierCost: arbitragePrice,
      platformFee,
      totalCharge: arbitragePrice + platformFee,
      currency: deal.currency || 'USD',
      savingsVsRetail: deal.gross_savings || 0,
    }};
  }}

  /**
   * Process payment and report to ANASTASiA.
   */
  async processPayment({{ dealId, amountCents, paymentMethodId, customerEmail, metadata = {{}} }}) {{
    // Step 1: Charge via {payment_processor}
    const paymentResult = await this._charge({{
      amountCents,
      paymentMethodId,
      customerEmail,
      metadata: {{ deal_id: dealId, source: 'anastasia', ...metadata }},
    }});

    // Step 2: Report to ANASTASiA
    if (paymentResult.success) {{
      await this.anastasia.http.post('/payments/report', {{
        deal_id: dealId,
        payment_id: paymentResult.paymentId,
        amount_cents: amountCents,
        processor: '{payment_processor}',
      }});
    }}

    return paymentResult;
  }}

  async _charge(params) {{
    // Wire this to your existing {payment_processor} charge logic
    throw new Error('Implement _charge with your {payment_processor} integration');
  }}
}}

module.exports = ANASTASiAPaymentAdapter;
'''

JS_EXPRESS_BOOKING_ROUTE = '''\
/**
 * ANASTASiA Booking Routes — Express router for deal search and booking.
 *
 * Generated by ANASTASiA Integrator v1.0
 */

const express = require('express');
const router = express.Router();
const ANASTASiAClient = require('./anastasiaClient');

const client = new ANASTASiAClient();

/**
 * Middleware: require authentication for booking routes.
 */
function requireAuth(req, res, next) {{
  if (!req.session || !req.session.userId) {{
    return res.status(401).json({{ error: 'Authentication required' }});
  }}
  next();
}}

/**
 * POST /anastasia/search
 * Search for flights or hotels with price arbitrage.
 */
router.post('/search', async (req, res) => {{
  const {{ vertical = 'flights', ...params }} = req.body;

  try {{
    let results;
    if (vertical === 'flights') {{
      results = await client.searchFlights(params);
    }} else if (vertical === 'hotels') {{
      results = await client.searchHotels(params);
    }} else {{
      return res.status(400).json({{ error: `Unknown vertical: ${{vertical}}` }});
    }}
    res.json(results);
  }} catch (err) {{
    console.error('ANASTASiA search failed:', err.message);
    res.status(503).json({{ error: 'Search temporarily unavailable' }});
  }}
}});

/**
 * GET /anastasia/deals/:dealId
 * Retrieve a specific deal.
 */
router.get('/deals/:dealId', async (req, res) => {{
  try {{
    const deal = await client.getDeal(req.params.dealId);
    res.json(deal);
  }} catch (err) {{
    console.error('Deal fetch failed:', err.message);
    res.status(404).json({{ error: 'Deal not found' }});
  }}
}});

/**
 * POST /anastasia/book
 * Book a deal (requires authentication).
 */
router.post('/book', requireAuth, async (req, res) => {{
  const {{ deal_id, passengers, payment_token }} = req.body;
  if (!deal_id) {{
    return res.status(400).json({{ error: 'deal_id required' }});
  }}

  try {{
    const booking = await client.createBooking({{
      dealId: deal_id,
      passengers: passengers || [],
      paymentToken: payment_token,
    }});
    res.status(201).json(booking);
  }} catch (err) {{
    console.error('Booking failed:', err.message);
    res.status(500).json({{ error: 'Booking failed' }});
  }}
}});

/**
 * GET /anastasia/bookings/:bookingId
 * Check booking status (requires authentication).
 */
router.get('/bookings/:bookingId', requireAuth, async (req, res) => {{
  try {{
    const status = await client.getBookingStatus(req.params.bookingId);
    res.json(status);
  }} catch (err) {{
    console.error('Status check failed:', err.message);
    res.status(404).json({{ error: 'Booking not found' }});
  }}
}});

module.exports = router;
'''

JS_NEXTJS_SEARCH_COMPONENT = '''\
/**
 * ANASTASiA Search Component — React component for Next.js.
 *
 * Drop-in flight/hotel search with deal cards showing arbitrage savings.
 *
 * Generated by ANASTASiA Integrator v1.0
 */

import {{ useState }} from 'react';

export default function ANASTASiASearch() {{
  const [vertical, setVertical] = useState('flights');
  const [results, setResults] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const [form, setForm] = useState({{
    origin: '',
    destination: '',
    departureDate: '',
    returnDate: '',
    adults: 1,
    cabinClass: 'ECONOMY',
  }});

  const handleSearch = async (e) => {{
    e.preventDefault();
    setLoading(true);
    setError(null);

    try {{
      const res = await fetch('/api/anastasia/search', {{
        method: 'POST',
        headers: {{ 'Content-Type': 'application/json' }},
        body: JSON.stringify({{ vertical, ...form }}),
      }});

      if (!res.ok) throw new Error('Search failed');
      const data = await res.json();
      setResults(data.deals || data.results || []);
    }} catch (err) {{
      setError(err.message);
    }} finally {{
      setLoading(false);
    }}
  }};

  return (
    <div className="anastasia-search">
      <h2>Search Deals</h2>

      <div className="tabs">
        <button onClick={{() => setVertical('flights')}}
                className={{vertical === 'flights' ? 'active' : ''}}>
          Flights
        </button>
        <button onClick={{() => setVertical('hotels')}}
                className={{vertical === 'hotels' ? 'active' : ''}}>
          Hotels
        </button>
      </div>

      <form onSubmit={{handleSearch}}>
        <input
          placeholder="Origin (e.g., JFK)"
          value={{form.origin}}
          onChange={{(e) => setForm({{ ...form, origin: e.target.value }})}}
          required
        />
        <input
          placeholder="Destination (e.g., LHR)"
          value={{form.destination}}
          onChange={{(e) => setForm({{ ...form, destination: e.target.value }})}}
          required
        />
        <input
          type="date"
          value={{form.departureDate}}
          onChange={{(e) => setForm({{ ...form, departureDate: e.target.value }})}}
          required
        />
        <input
          type="date"
          value={{form.returnDate}}
          onChange={{(e) => setForm({{ ...form, returnDate: e.target.value }})}}
        />
        <button type="submit" disabled={{loading}}>
          {{loading ? 'Searching...' : 'Find Deals'}}
        </button>
      </form>

      {{error && <div className="error">{{error}}</div>}}

      <div className="results">
        {{results.map((deal, i) => (
          <div key={{deal.id || i}} className="deal-card">
            <div className="route">
              {{deal.origin}} &rarr; {{deal.destination}}
            </div>
            <div className="prices">
              <span className="retail">Retail: ${{deal.home_price}}</span>
              <span className="our-price">Our Price: ${{deal.arbitrage_price + deal.platform_fee_usd}}</span>
            </div>
            <div className="savings">
              You save: ${{deal.user_savings}} ({{deal.user_saves_pct}}%)
            </div>
            <button onClick={{() => window.location.href = `/book/${{deal.id}}`}}>
              Book Now
            </button>
          </div>
        ))}}
      </div>
    </div>
  );
}}
'''

# --- Config file templates ---

PYTHON_CONFIG = '''\
"""
ANASTASiA Configuration — {framework} integration.

Set these environment variables or update this file directly.

Generated by ANASTASiA Integrator v1.0
"""

import os


class ANASTASiAConfig:
    """Configuration for ANASTASiA integration."""

    # API credentials (get these from your ANASTASiA dashboard)
    API_KEY = os.environ.get("ANASTASIA_API_KEY", "")
    AGENCY_ID = os.environ.get("ANASTASIA_AGENCY_ID", "")
    BASE_URL = os.environ.get(
        "ANASTASIA_BASE_URL",
        "https://api.anastasia.mystes.app/v1"
    )

    # Feature flags
    FLIGHTS_ENABLED = os.environ.get("ANASTASIA_FLIGHTS", "true").lower() == "true"
    HOTELS_ENABLED = os.environ.get("ANASTASIA_HOTELS", "false").lower() == "true"

    # Payment integration
    PAYMENT_PROCESSOR = "{payment_processor}"
    AUTO_SPLIT_FEES = True  # Automatically split ANASTASiA fees from supplier cost

    # Caching
    CACHE_TTL_SECONDS = int(os.environ.get("ANASTASIA_CACHE_TTL", "300"))

    # Logging
    LOG_LEVEL = os.environ.get("ANASTASIA_LOG_LEVEL", "INFO")
'''

JS_CONFIG = '''\
/**
 * ANASTASiA Configuration — {framework} integration.
 *
 * Generated by ANASTASiA Integrator v1.0
 */

module.exports = {{
  // API credentials (set via environment variables)
  apiKey: process.env.ANASTASIA_API_KEY || '',
  agencyId: process.env.ANASTASIA_AGENCY_ID || '',
  baseURL: process.env.ANASTASIA_BASE_URL || 'https://api.anastasia.mystes.app/v1',

  // Feature flags
  flightsEnabled: process.env.ANASTASIA_FLIGHTS !== 'false',
  hotelsEnabled: process.env.ANASTASIA_HOTELS === 'true',

  // Payment integration
  paymentProcessor: '{payment_processor}',
  autoSplitFees: true,

  // Caching
  cacheTTL: parseInt(process.env.ANASTASIA_CACHE_TTL || '300', 10),

  // Logging
  logLevel: process.env.ANASTASIA_LOG_LEVEL || 'info',
}};
'''


# ---------------------------------------------------------------------------
# Payment-specific import lines
# ---------------------------------------------------------------------------

PAYMENT_IMPORTS = {
    "stripe": 'import stripe\n\nstripe.api_key = os.environ.get("STRIPE_SECRET_KEY", "")',
    "paypal": 'import paypalrestsdk\n\npaypalrestsdk.configure({"mode": os.environ.get("PAYPAL_MODE", "sandbox")})',
    "square": 'from square.client import Client as SquareClient',
    "adyen": 'import Adyen',
    "braintree": 'import braintree',
}


class CodeGenerator:
    """
    Generates native integration code for a customer's detected tech stack.

    Given a TechStack (from CodebaseAnalyzer) and a SystemProfile (what the
    customer connects to), produces ready-to-use source files as ActionProposal
    objects for admin review.

    Supports code generation in: Python, JavaScript/TypeScript, PHP, Java,
    Ruby, and Go. Uses string template substitution with realistic,
    production-quality code patterns.

    Usage:
        generator = CodeGenerator(event_bus)
        proposals = generator.generate_integration(tech_stack, system_profile)
        # Each proposal contains the generated code in proposal.diff
    """

    def __init__(self, event_bus: EventBus):
        """
        Initialize the code generator.

        Args:
            event_bus: Shared event bus for publishing generation events.
        """
        self._event_bus = event_bus

    def generate_integration(
        self,
        tech_stack: TechStack,
        system_profile: SystemProfile,
        template_name: Optional[str] = None,
    ) -> List[ActionProposal]:
        """
        Generate all integration files as ActionProposal objects.

        Produces an API client, payment adapter, booking route handler,
        search component (if UI framework detected), and configuration file,
        all in the customer's detected language and framework patterns.

        Args:
            tech_stack: Detected technology stack of customer's platform.
            system_profile: Profile of the system being integrated.
            template_name: Optional specific template to use (overrides auto-detect).

        Returns:
            List of ActionProposal objects, each containing a generated file.
        """
        proposals = []
        language = tech_stack.language or "python"
        framework = tech_stack.framework or "flask"
        payment = tech_stack.detected_files.get("payment_system", "stripe")

        # --- API Client ---
        client_code = self.generate_api_client(tech_stack, system_profile)
        if client_code:
            ext = self._file_extension(language)
            proposals.append(ActionProposal(
                agency_id=system_profile.id if system_profile else "",
                action_type="file_create",
                description=f"Create ANASTASiA API client ({language}/{framework})",
                files_affected=[f"anastasia_client{ext}"],
                diff=client_code,
                risk_level="low",
                rollback_plan=f"Delete anastasia_client{ext}",
            ))

        # --- Payment Adapter ---
        payment_code = self.generate_payment_adapter(tech_stack, payment)
        if payment_code:
            ext = self._file_extension(language)
            proposals.append(ActionProposal(
                agency_id=system_profile.id if system_profile else "",
                action_type="file_create",
                description=f"Create payment adapter ({payment} -> ANASTASiA)",
                files_affected=[f"anastasia_payment{ext}"],
                diff=payment_code,
                risk_level="medium",
                rollback_plan=f"Delete anastasia_payment{ext}",
            ))

        # --- Booking Route ---
        route_code = self.generate_booking_route(tech_stack, system_profile)
        if route_code:
            ext = self._file_extension(language)
            proposals.append(ActionProposal(
                agency_id=system_profile.id if system_profile else "",
                action_type="file_create",
                description=f"Create booking routes ({framework})",
                files_affected=[f"anastasia_routes{ext}"],
                diff=route_code,
                risk_level="low",
                rollback_plan=f"Delete anastasia_routes{ext}",
            ))

        # --- Search Component (if UI framework detected) ---
        if tech_stack.ui_framework:
            search_code = self.generate_search_component(
                tech_stack, tech_stack.ui_framework
            )
            if search_code:
                comp_ext = self._component_extension(
                    language, tech_stack.ui_framework
                )
                proposals.append(ActionProposal(
                    agency_id=system_profile.id if system_profile else "",
                    action_type="file_create",
                    description=f"Create search component ({tech_stack.ui_framework})",
                    files_affected=[f"ANASTASiASearch{comp_ext}"],
                    diff=search_code,
                    risk_level="low",
                    rollback_plan=f"Delete ANASTASiASearch{comp_ext}",
                ))

        # --- Config File ---
        config_code = self.generate_config_file(tech_stack)
        if config_code:
            ext = self._file_extension(language)
            proposals.append(ActionProposal(
                agency_id=system_profile.id if system_profile else "",
                action_type="file_create",
                description=f"Create ANASTASiA configuration ({framework})",
                files_affected=[f"anastasia_config{ext}"],
                diff=config_code,
                risk_level="low",
                rollback_plan=f"Delete anastasia_config{ext}",
            ))

        # Publish event
        self._event_bus.publish(Event(
            type=EventType.INTEGRATION_STARTED,
            source="integrator.generator",
            data={
                "language": language,
                "framework": framework,
                "files_generated": len(proposals),
                "system_name": system_profile.name if system_profile else "",
            },
        ))

        logger.info(
            "Generated %d integration files for %s/%s",
            len(proposals), language, framework,
        )

        return proposals

    def generate_api_client(
        self, tech_stack: TechStack, system_profile: SystemProfile
    ) -> str:
        """
        Generate an API client in the target language.

        The client handles authentication, search, booking, and error
        recovery against the ANASTASiA API.

        Args:
            tech_stack: Customer's detected tech stack.
            system_profile: System being integrated.

        Returns:
            Generated source code as a string.
        """
        language = tech_stack.language or "python"
        system_name = system_profile.name if system_profile else "ANASTASiA"

        template = self._get_language_template(language, "api_client")
        if not template:
            logger.warning("No API client template for language: %s", language)
            return ""

        return template.format(
            system_name=system_name,
            payment_processor=self._detect_payment_from_stack(tech_stack),
        )

    def generate_payment_adapter(
        self, tech_stack: TechStack, payment_processor: str
    ) -> str:
        """
        Generate a payment adapter bridging their processor to ANASTASiA fees.

        Args:
            tech_stack: Customer's detected tech stack.
            payment_processor: Detected payment processor name.

        Returns:
            Generated source code as a string.
        """
        language = tech_stack.language or "python"
        processor = payment_processor or "stripe"

        template = self._get_language_template(language, "payment_adapter")
        if not template:
            logger.warning(
                "No payment adapter template for language: %s", language
            )
            return ""

        payment_import = PAYMENT_IMPORTS.get(processor, f"# TODO: Import {processor} SDK")

        return template.format(
            payment_processor=processor,
            payment_import=payment_import,
        )

    def generate_booking_route(
        self, tech_stack: TechStack, system_profile: SystemProfile
    ) -> str:
        """
        Generate a booking route handler for the customer's framework.

        Creates search, deal retrieval, booking, and status check endpoints
        in the customer's web framework conventions.

        Args:
            tech_stack: Customer's detected tech stack.
            system_profile: System being integrated.

        Returns:
            Generated source code as a string.
        """
        language = tech_stack.language or "python"

        template = self._get_language_template(language, "booking_route")
        if not template:
            logger.warning(
                "No booking route template for language: %s", language
            )
            return ""

        return template.format(
            system_name=(system_profile.name if system_profile else "ANASTASiA"),
            payment_processor=self._detect_payment_from_stack(tech_stack),
        )

    def generate_search_component(
        self, tech_stack: TechStack, ui_framework: str
    ) -> str:
        """
        Generate a search UI component for the customer's frontend framework.

        Args:
            tech_stack: Customer's detected tech stack.
            ui_framework: Detected UI framework (react, vue, angular, etc.).

        Returns:
            Generated source code as a string.
        """
        template = self._get_language_template(ui_framework, "search_component")
        if not template:
            # Fall back to React as the most common
            if ui_framework in ("react", "vue", "angular", "svelte"):
                template = JS_NEXTJS_SEARCH_COMPONENT
            else:
                logger.warning(
                    "No search component template for UI framework: %s",
                    ui_framework,
                )
                return ""

        return template.format(
            system_name="ANASTASiA",
            payment_processor=self._detect_payment_from_stack(tech_stack),
        )

    def generate_config_file(self, tech_stack: TechStack) -> str:
        """
        Generate an ANASTASiA configuration file for the customer's stack.

        Args:
            tech_stack: Customer's detected tech stack.

        Returns:
            Generated configuration code as a string.
        """
        language = tech_stack.language or "python"
        framework = tech_stack.framework or "flask"
        payment = self._detect_payment_from_stack(tech_stack)

        if language in ("python",):
            return PYTHON_CONFIG.format(
                framework=framework,
                payment_processor=payment,
            )
        elif language in ("javascript", "typescript"):
            return JS_CONFIG.format(
                framework=framework,
                payment_processor=payment,
            )
        else:
            # Generic JSON config for other languages
            return self._generic_json_config(framework, payment)

    def _get_language_template(self, language: str, component: str) -> str:
        """
        Get the code template for a given language and component.

        Args:
            language: Target language or UI framework.
            component: Component type (api_client, payment_adapter, etc.).

        Returns:
            Template string, or empty string if not available.
        """
        templates = {
            ("python", "api_client"): PYTHON_FLASK_API_CLIENT,
            ("python", "payment_adapter"): PYTHON_FLASK_PAYMENT_ADAPTER,
            ("python", "booking_route"): PYTHON_FLASK_BOOKING_ROUTE,
            ("javascript", "api_client"): JS_EXPRESS_API_CLIENT,
            ("javascript", "payment_adapter"): JS_EXPRESS_PAYMENT_ADAPTER,
            ("javascript", "booking_route"): JS_EXPRESS_BOOKING_ROUTE,
            ("typescript", "api_client"): JS_EXPRESS_API_CLIENT,
            ("typescript", "payment_adapter"): JS_EXPRESS_PAYMENT_ADAPTER,
            ("typescript", "booking_route"): JS_EXPRESS_BOOKING_ROUTE,
            ("react", "search_component"): JS_NEXTJS_SEARCH_COMPONENT,
            ("vue", "search_component"): JS_NEXTJS_SEARCH_COMPONENT,  # Placeholder
        }

        return templates.get((language, component), "")

    # -------------------------------------------------------------------
    # Private helpers
    # -------------------------------------------------------------------

    def _detect_payment_from_stack(self, tech_stack: TechStack) -> str:
        """Extract payment processor from tech stack detected files."""
        # Check detected_files for payment info
        for filename, purpose in tech_stack.detected_files.items():
            if "payment" in purpose.lower():
                return purpose.split(":")[-1].strip() if ":" in purpose else "stripe"
        return "stripe"  # Default

    def _file_extension(self, language: str) -> str:
        """Get the standard file extension for a language."""
        extensions = {
            "python": ".py",
            "javascript": ".js",
            "typescript": ".ts",
            "java": ".java",
            "ruby": ".rb",
            "php": ".php",
            "go": ".go",
            "csharp": ".cs",
            "kotlin": ".kt",
            "rust": ".rs",
            "elixir": ".ex",
            "scala": ".scala",
            "swift": ".swift",
        }
        return extensions.get(language, ".txt")

    def _component_extension(self, language: str, ui_framework: str) -> str:
        """Get the file extension for a UI component."""
        if ui_framework == "react":
            return ".tsx" if language == "typescript" else ".jsx"
        elif ui_framework == "vue":
            return ".vue"
        elif ui_framework == "svelte":
            return ".svelte"
        elif ui_framework == "angular":
            return ".component.ts"
        return ".jsx"

    def _generic_json_config(self, framework: str, payment: str) -> str:
        """Generate a generic JSON config for unsupported languages."""
        import json
        config = {
            "_comment": f"ANASTASiA Configuration — {framework} integration",
            "_generated_by": "ANASTASiA Integrator v1.0",
            "api_key": "${ANASTASIA_API_KEY}",
            "agency_id": "${ANASTASIA_AGENCY_ID}",
            "base_url": "https://api.anastasia.mystes.app/v1",
            "features": {
                "flights": True,
                "hotels": False,
            },
            "payment": {
                "processor": payment,
                "auto_split_fees": True,
            },
            "cache_ttl_seconds": 300,
            "log_level": "info",
        }
        return json.dumps(config, indent=2)
